### ISSUE TITLE
时不时的失效，无法去除广告

### ISSUE THREAD

**Issue by hopana** [HaoNShi/Tampermonkey_Scripts#1]

**Comment by HaoNShi** [comment]
您好，能麻烦您提供一下更详细的描述吗？请问使用的是什么浏览器和插件，遇到问题的网站和具体情况是什么？

**Comment by hopana** [comment]
这个问题不一定能重现，我现在试了几次都OK。之前的场景是：

打开百度搜索的时候，时不时发现搜索列表里面有广告，有时候又没有，有时候会闪一下。
系统：win10
浏览器：360极速浏览器
插件：油猴



hopana@163.com
 
发件人： HaoNShi
发送时间： 2020-05-09 16:01
收件人： HaoNShi/Tampermonkey_Scripts
抄送： 糊糊; Author
主题： Re: [HaoNShi/Tampermonkey_Scripts] 时不时的失效，无法去除广告 (#1)
您好，能麻烦您提供一下更详细的描述吗？请问使用的是什么浏览器和插件，遇到问题的网站和具体情况是什么？
